### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by opokualbert** [SimFin/simfin-tutorials#3]
I run this code and I am getting an error:

    import simfin as sf
    sf.set_api_key(api_key='free')
    df_prices = sf.load_shareprices(variant='daily', market='us')

Here is the error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-d968c738d8e3> in <module>
     11 
     12 # %%time
---> 13 df_prices = sf.load_shareprices(variant='daily', market='us')

~\Miniconda3\lib\site-packages\simfin\load.py in load(dataset, variant, market, parse_dates, index, refresh_days)
    130 
    131     # Download file if it does not exist on local disk, or if it is too old.
--> 132     _maybe_download_dataset(**dataset_args, refresh_days=refresh_days)
    133 
    134     # Lambda function for converting strings to dates. Format: YYYY-MM-DD

~\Miniconda3\lib\site-packages\simfin\download.py in _maybe_download_dataset(refresh_days, **kwargs)
    281 
    282     # Full path for the local data-file.
--> 283     path = _path_dataset(**kwargs)
    284 
    285     # Full path for the downloaded file.

~\Miniconda3\lib\site-packages\simfin\paths.py in _path_dataset(**kwargs)
     66     """
     67     filename = _filename_dataset(extension='csv', **kwargs)
---> 68     path = os.path.join(get_data_dir(), filename)
     69     return path
     70 

~\Miniconda3\lib\ntpath.py in join(path, *paths)
     74 # Join two (or more) paths.
     75 def join(path, *paths):
---> 76     path = os.fspath(path)
     77     if isinstance(path, bytes):
     78         sep = b'\\'

TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by Hvass-Labs** [comment]
You need to set the data-dir before calling any of the `sf.load` functions. Like this:

    import simfin as sf
    sf.set_api_key(api_key='free')
    sf.set_data_dir('~/simfin_data/')  # THIS WAS MISSING!
    df_prices = sf.load_shareprices(variant='daily', market='us')

Let me know if this solves the problem.

**Comment by opokualbert** [comment]
@Hvass-Labs Thank you that worked.
A quick question is there a difference between the API key I have now and the 'free'? I put in my API and it says I should use the free because I do not have simfin+ API. Does that mean until I subscribe, the API is useless? 
Again I want to say this is a useful package and so make it possible to donate to the project if we are not able to subscribe to a monthly 19 euros.

**Comment by Hvass-Labs** [comment]
If you are using the Python API then there is no difference between using the 'free' API key, and an API-key you have obtained on the SimFin website but you haven't yet paid for a SimFin+ subscription. So you don't really need an API-key unless you are going to buy a SimFin+ subscription as well.

However, if you want to use SimFin's old web-API system instead of the new Python API, then you need an API key just to get the web-API working, even if you don't buy a SimFin+ subscription.

Currently there is no donation-option to the project. But a suggestion would be to subscribe for a single month and then unsubscribe again. That way you can also download the entire dataset for a month using your SimFin+ API-key.

PS: I have edited your original post so it is easier to read. Please note the special GitHub / Markdown syntax for proper formatting, which makes it easier for other people to read.

**Comment by opokualbert** [comment]
Thanks for you response
